version: '3.8'

services:
  flask:
    build: .
    container_name: flask-app
    expose:
      - 5000
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
